version: '3.4'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql.test.atdd
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_OUT}:3306"
    volumes:
      - "../../config/mysql/conf:/etc/mysql/conf.d"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mock-server:
    image: 'mockserver/mockserver:5.13.2'
    container_name: mock-server.test.atdd
    ports:
      - "${MOCK_SERVER_PORT_OUT}:1080"
    command: [ "-serverPort", "1080", "-logLevel", "INFO" ]
    healthcheck:
      test: [ "CMD", "nc" ,"-z", "localhost", "1080" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.test.atdd
    links:
      - mysql:db
    ports:
      - "${PHPMYADMIN_PORT_OUT}:80"

  selenium-standalone-chrome4:
    image: selenium/standalone-chrome:4.0.0-beta-3-20210426
    container_name: web-driver.test.atdd
    ports:
      - '4444:4444'
      - '7900:7900'
    extra_hosts:
      - "api.net:${HOST_NAME:-127.0.0.1}"
      - "host.docker.internal:host-gateway"
    environment:
      - VNC_NO_PASSWORD=1

  web-driver_video:
    image: josephyao/selenium-video-ffmpeg:v0.0.3
    volumes:
      - ../../videos:/videos
    depends_on:
      - selenium-standalone-chrome4
    ports:
      - "9000:9000"
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-standalone-chrome4
