stages:
  - test

test:
  stage: test
  image: docker:18.09.8
  services:
    - docker:18.09.8-dind
  script:
    - apk add --no-cache docker-compose
    - sh dev-ops/env-test config
    - sh dev-ops/env-test up -d
    - sh dev-ops/core/bin/env-exec test nodejs courses/attd-v2/frontend/ ls src
    - dev-ops/core/bin/env-exec test nodejs courses/attd-v2/frontend/ ls src
    #- apk add --no-cache bash docker-compose
    #- bash dev-ops/dc_ci up -d
    #- bash dev-ops/dc_ci exec -T nodejs npm install --prefix /opt/current/attd-v2/frontend
    #- bash dev-ops/dc_ci exec -T nodejs npm run serve --prefix /opt/current/attd-v2/frontend &
    #- bash dev-ops/dc_ci exec -T jdk /opt/current/attd-v2/dev-ops/gradlew test cucumber

