stages:
  - test

test:
  stage: test
  image: docker:20.10.2
  services:
    - docker:20.10.2-dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose -f env/compose/dc_pc/docker-compose.yml up -d
    - docker-compose -f env/compose/dc_pc/docker-compose.yml exec -T nodejs yarn
    - docker-compose -f env/compose/dc_pc/docker-compose.yml exec -T nodejs yarn serve &
    - docker-compose -f env/compose/dc_pc/docker-compose.yml exec -T jdk ./gradlew backend:bootRun --args='--spring.profiles.active=standalone-dev' &
    - docker-compose -f env/compose/dc_pc/docker-compose.yml exec -T jdk ./gradlew test cucumber

