variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - if [ ! -z "${CI_COMMIT_SHA}" ]; then export APP_VERSION="${CI_COMMIT_SHA:0:8}"; fi
  - if [ ! -z "${CI_COMMIT_TAG}" ]; then export APP_VERSION="${CI_COMMIT_TAG}"; fi

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test

test:
  stage: test
  image: docker:18.09.8-dind
  script:
    - cat /etc/hosts
    - apk add --no-cache build-base nss libffi-dev openssl-dev npm openjdk11
    - cd frontend && npm install && ( npm run serve & )
    - cd ..
    - export RUNNING_CODE_IP=$(hostname -i)
    - bash env/setup_host.sh $RUNNING_CODE_IP
    - cat /etc/hosts
    - env/dc_pc up -d
    - bash env/setup_web.sh $RUNNING_CODE_IP
    - docker exec -i web-driver sudo cat /etc/hosts
    - ./gradlew test cucumber -x npmSetup -x npmInstall -x nodeSetup -x :frontend:clean -x :frontend:npmBuild

