stages:
  - test

test:
  stage: test
  image: docker:18.09.8
  services:
    - docker:18.09.8-dind
  script:
    - apk add --no-cache docker-compose
    - dev-ops/env-test config
    - dev-ops/env-test up -d
    - dev-ops/core/bin/env-exec test nodejs frontend npm install
    - dev-ops/core/bin/env-exec test nodejs frontend npm run serve
    - dev-ops/core/bin/env-exec test jdk ./ ./gradlew cucumber

