x-mysql8: &mysql8
  image: mysql/mysql-server:8.0
  container_name: mysql.test.${PROJECT_NAME}
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  ports:
    - "3306:3306"
  volumes:
    - "../../configs/containers/mysql/conf:/etc/mysql/conf.d"
  healthcheck:
    test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    timeout: 20s
    retries: 10
  networks:
    default:
      aliases:
        - mysql.tool.net
